name: darasni
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.2+22

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Themes ,View,  styles
  google_fonts: any
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  image_picker: ^1.0.0
  time_zone_list: ^1.0.0
  intl: any
  url_launcher: ^6.1.14
  search_page: ^2.3.0
  flutter_spinkit:
  webview_flutter: ^4.0.0
  webview_flutter_wkwebview: ^3.9.1
  http_auth: ^1.0.3
#  in_app_review: ^2.0.8
  app_review:
  flutter_share_me: ^1.4.0
  flutter_keyboard_visibility: ^5.4.1
  local_auth: ^2.1.7
  flutter_share: ^2.0.0
  table_calendar: ^3.0.9


  #  State Management
  get: ^4.6.5

  #  Firebase

  # Http Request Handler
  http: ^0.13.0

  #Local Storage Handler
  get_storage: ^2.1.1

# Payment Gate Ways
#  flutter_paypal: ^0.2.0
#  flutter_tap_payment: ^0.2.0`


  # Others
  logger: ^1.3.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

dependency_overrides:
  package_info_plus: any


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/new_app_logo.png"
  min_sdk_android: 21





flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/flags/
    - assets/tutor.png
    - assets/student.png

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Font/Helvetica.ttf

